on:
  schedule:
    - cron: '15 15 * * *' # Staggered by 15 mins
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    container: rqthomas/vera-rocker:latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Install
        shell: Rscript {0}
        run: |
          install.packages(c("tidyverse", "lubridate"))

      - name: Generate forecasts
        shell: Rscript {0}
        run: |
          source("model_code/Secchi_RF_Dom/Secchi_lm_DXE.R")